# -*- coding: utf-8 -*-
"""Final_ML_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Eu84mO71Kmn6-0WG_ZdzeTgpefdt11_

**Setup and Installation**
"""

!pip install xgboost -q

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import time
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, confusion_matrix, roc_curve
)
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from xgboost import XGBClassifier
import joblib

sns.set_style('whitegrid')
# %matplotlib inline

"""**Loading the Dataset and Preprocessing**"""

df = pd.read_csv('final Dataset.csv')
print(df.head())
print(df.shape)

"""Preprocessing

"""

X = df.drop(columns=['label', 'URL'])
y = df['label']   # 1 = legitimate, 0 = phishing

# Drop any remaining non-numeric columns
non_numeric_cols = X.select_dtypes(include=['object']).columns

#These are irrevelant features as these need webpage access to determine which takes time
columns_to_remove = [
    'LineOfCode', 'LargestLineLength', 'HasTitle', 'Title',  'DomainTitleMatchScore', 'URLTitleMatchScore', 'HasFavicon', 'Robots',  'IsResponsive',  'HasDescription', 'NoOfPopup','NoOfiFrame', 'HasExternalFormSubmit',
    'HasSocialNet', 'HasSubmitButton', 'HasHiddenFields', 'HasPasswordField', 'Bank', 'Pay', 'Crypto', 'HasCopyrightInfo', 'NoOfImage', 'NoOfCSS', 'NoOfJS',  'NoOfSelfRef',  'NoOfEmptyRef',    'NoOfExternalRef','URLSimilarityIndex'
]

if len(non_numeric_cols) > 0:
    print(f"Dropping non-numeric: {list(non_numeric_cols)}")
    X = X.drop(columns=non_numeric_cols)

X = X.drop(columns=[col for col in columns_to_remove if col in X.columns])

# Fill missing values with median
X = X.fillna(X.median())

print("Features shape:", X.shape)
print("Label distribution:\n", y.value_counts())

"""**Train-Test Split and Scaling**

"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Scaler for Logistic Regression only
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"Train: {X_train.shape[0]} samples")
print(f"Test:  {X_test.shape[0]} samples")

"""**Model Training and Selection**"""

# Logistic Regression with L2 regularization
lr = LogisticRegression(C=0.1, max_iter=1000, random_state=42)

# Random Forest with restrictions
rf = RandomForestClassifier(
    n_estimators=100, max_depth=10, min_samples_split=20,
    min_samples_leaf=10, random_state=42, n_jobs=-1
)

# XGBoost with early stopping and regularization
xgb_clf = xgb.XGBClassifier(
    n_estimators=100, max_depth=5, learning_rate=0.05,
    subsample=0.8, colsample_bytree=0.8, reg_alpha=0.1, reg_lambda=1.0,
    use_label_encoder=False, eval_metric='logloss', random_state=42
)

models = {'Logistic Regression': lr, 'Random Forest': rf, 'XGBoost': xgb_clf}

for name, model in models.items():
    if name == 'Logistic Regression':
        model.fit(X_train_scaled, y_train)
        y_pred = model.predict(X_test_scaled)
    else:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    print(f"{name:20} | Test Acc: {acc:.4f} | F1: {f1:.4f}")

estimators = [('lr', lr), ('rf', rf), ('xgb', xgb_clf)]
stack = StackingClassifier(
    estimators=estimators,
    final_estimator=LogisticRegression(C=0.1),
    cv=5,   # cross-validation inside stacking
    stack_method='predict_proba'
)

stack.fit(X_train_scaled, y_train)
y_pred_stack = stack.predict(X_test_scaled)

print("\n===== Stacking Ensemble =====")
print(f"Accuracy: {accuracy_score(y_test, y_pred_stack):.4f}")
print(f"Precision: {precision_score(y_test, y_pred_stack):.4f}")
print(f"Recall: {recall_score(y_test, y_pred_stack):.4f}")
print(f"F1-score: {f1_score(y_test, y_pred_stack):.4f}")
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_stack))

"""Cross validate for checking overfitting"""

from sklearn.model_selection import cross_val_score
cv_scores = cross_val_score(stack, X_train_scaled, y_train, cv=5, scoring='accuracy')
print(f"5-fold CV accuracy on training set: {cv_scores.mean():.4f} (+/- {cv_scores.std():.4f})")


test_acc = accuracy_score(y_test, y_pred_stack)
print(f"Test accuracy: {test_acc:.4f}")
if test_acc < cv_scores.mean() - 0.02:
    print("⚠️ Possible overfitting – test accuracy lower than CV mean.")
else:
    print("✅ No severe overfitting detected.")

"""**Evaluation Metrics**"""

y_proba = stack.predict_proba(X_test_scaled)[:, 1]

from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score,
                             roc_auc_score, confusion_matrix, classification_report)
import time

# Assuming y_test (true labels) and y_pred (predictions), and y_proba (probabilities)
acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred)
rec = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
specificity = confusion_matrix(y_test, y_pred)[0,0] / (confusion_matrix(y_test, y_pred)[0,0] + confusion_matrix(y_test, y_pred)[0,1])
auc = roc_auc_score(y_test, y_proba)

print(f"Accuracy: {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall: {rec:.4f}")
print(f"F1: {f1:.4f}")
print(f"Specificity: {specificity:.4f}")
print(f"ROC‑AUC: {auc:.4f}")


# Inference time
start = time.time()
for _ in range(1000):
    _ = stack.predict(X_test_scaled[:1])
avg_time = (time.time() - start) / 1000 * 1000  # ms
print(f"Avg inference time: {avg_time:.2f} ms")

"""**Model Saving**"""

# Save model and scaler
joblib.dump(stack, 'phishguard_model_final.pkl')
joblib.dump(scaler, 'scaler_final.pkl')
joblib.dump(X.columns.tolist(), 'feature_columns_final.pkl')

from google.colab import files
files.download('phishguard_model_final.pkl')
files.download('scaler_final.pkl')
files.download('feature_columns_final.pkl')
print("Model and scaler downloaded.")

X_train.columns

